// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_4p1a0eJS_YL1b1qTvGl6UIzvqaZeYl4',
    appId: '1:931311274884:web:176bda55601956453c6bd1',
    messagingSenderId: '931311274884',
    projectId: 'bestmlawi-5b005',
    authDomain: 'bestmlawi-5b005.firebaseapp.com',
    databaseURL: 'https://bestmlawi-5b005-default-rtdb.firebaseio.com',
    storageBucket: 'bestmlawi-5b005.firebasestorage.app',
    measurementId: 'G-BS0RM5B4MH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeu2k5wE4W1v7C4RWsegSodVJMmqtDN5M',
    appId: '1:931311274884:android:7614177aae80cf083c6bd1',
    messagingSenderId: '931311274884',
    projectId: 'bestmlawi-5b005',
    databaseURL: 'https://bestmlawi-5b005-default-rtdb.firebaseio.com',
    storageBucket: 'bestmlawi-5b005.firebasestorage.app',
  );

}